config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}

  namespace :admin do
    root :to => 'home#index'
    resources :admins
    resources :users, only: :index
    resources :posts, only: [:index, :show]
  end

  root to: "user/timeline#index"

  namespace :user do
    get 'profile', to: "profile#show"
    resources :posts, only: :create
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, :name, :avatar, presence: true

  has_one_attached :avatar
  has_many :posts
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < AdminController
  before_action :set_admin, only: [:edit, :update, :destroy]
  
  def index
    @admins = Admin.order(id: :desc)
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(form_params)

    if @admin.save
      redirect_to admin_admins_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    params = form_params.to_h
    params = params.except!(:password, :password_confirmation) if params[:password].blank?

    if @admin.update(params)
      redirect_to admin_admins_path
    else
      render :edit
    end
  end

  def destroy
    @admin.destroy
    redirect_to admin_admins_path
  end

  private
  
  def form_params
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end
end 

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

  def index
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end
end 

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.order(id: :desc)
  end
end 

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin

  def authenticate_admin
    redirect_to new_admin_session_path unless current_admin?
  end

  def current_admin?
    if current_admin.present? 
      true
    else
      false
    end
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  
  def after_sign_out_path_for(admin)
    new_admin_session_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController

  def create
    f_params = form_params.merge(user: current_user)

    @post = Post.new(f_params)

    if @post.save
      redirect_to user_profile_path
    else
      render "user/profile/show"
    end
  end

  private
  
  def form_params
    params.require(:post).permit(:body)
  end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController

  def show
    @post = Post.new
  end

end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController

  def index
    
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user

  def authenticate_user
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :name, :avatar])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/_form.html.erb
<div class="card" style="background-color:#f6f6f6;">
  <div class="card-body">
    <%= form_with(model: [:admin, admin], local: true) do |f| %>
      <%= render "layouts/form_errors", record: admin %>
      <div class="form-group">
        <label>Nome</label>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="form-group">
        <label>Email</label>
        <%= f.email_field :email, class: "form-control"%>
      </div>
      <div class="form-row">
        <div class="col-6">
          <div class="form-group">
            <label>Senha</label>
            <%= f.password_field :password, class: "form-control"%>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <label>Confirmar Senha</label>
            <%= f.password_field :password_confirmation, class: "form-control"%>
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Salvar</button>
      <%= link_to("Cancelar", admin_admins_path, class: "btn btn-secondary ml-3")%>
    <% end %>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<h2>Editar Administrador #<%= @admin.id %></h2>
<%= render 'form', admin: @admin %>

app/views/admin/admins/index.html.erb
<%= link_to("Adicionar Administrador", new_admin_admin_path, class: "btn btn-success mb-4")%>
<h4>Admins</h4>
<br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Criado em:</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <th scope="row"><%= admin.id %></th>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.created_at %></td>
        <td><%= link_to("Editar", edit_admin_admin_path(admin), class: "btn btn-warning btn-sm")%></td>
        <td><%= link_to("Deletar", admin_admin_path(admin), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm")%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<h2>Novo Administrador</h2>
<%= render 'form', admin: @admin %>

app/views/admin/home/index.html.erb
<h2>Fala ae parça, admin</h2>

app/views/admin/posts/index.html.erb
<h4>Posts</h4>
<br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Autor</th>
      <th scope="col">Texto</th>
      <th scope="col">Criado em:</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= post.user.name %></td>
        <td><%= link_to post.body.truncate(30), admin_post_path(post) %></td>
        <td><%= post.created_at.strftime("%d/%m/%Y %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/show.html.erb
<h4>Post: <%= @post.id %> - Criado por: <%= @post.user.name %></h4>
<div class="card text-white bg-dark mb-3 mt-3">
  <div class="card-header"><%= @post.user.name %></div>
  <div class="card-body">
    <small class="text-muted"><%= @post.created_at.strftime("%d/%m/%T - %H:%M") %></small>
    <p class="card-text"><%= @post.body %></p>
  </div>
</div>

app/views/admin/users/index.html.erb
<h4>Usuários</h4>
<br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Avatar</th>
      <th scope="col">Nome</th>
      <th scope="col">Telefone</th>
      <th scope="col">Email</th>
      <th scope="col">Criado em:</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= image_tag(user.avatar, alt: "Avatar", class: 'ui-w-100-forced rounded-circle', style: "height:30px; width:30px") %></td>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%d/%m/%Y %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_form_errors.html.erb
<% if record && record.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= t('.error_on_save') %></h4>
    <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<% content_for :content do %>
  <%= render "layouts/admin/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path)? "active" : ""%>">
        <%= link_to("Home", admin_root_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_admins_path)? "active" : ""%>">
        <%= link_to("Administradores", admin_admins_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_users_path)? "active" : ""%>">
        <%= link_to("Usuários", admin_users_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_posts_path)? "active" : ""%>">
        <%= link_to("Posts", admin_posts_path, class: "nav-link") %>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_admin.email %></div>
        </li>
        <li class="nav-item">
          <%= link_to("Sair", destroy_admin_session_path, method: :delete, class: "nav-link") %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height:100%;">
  <head>
    <title>SocialNetworking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="height:100%;">
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<% content_for :content do %>
  <%= render "layouts/user/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/user/_header.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark" style="background-color:#000080!important;">
  <div class="container" >
    <%= image_tag("logo.png", alt: "logo", class: 'navbar-brand', style: "height:40px;")%>
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(root_path)? "active" : ""%>">
        <%= link_to("Timeline", root_path, class: "nav-link") %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Followers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Following</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Quem eu posso seguir</a>
      </li>
      <li class="nav-item <%= current_page?(user_profile_path)? "active" : ""%>">
        <%= link_to("Meu perfil", user_profile_path, class: "nav-link") %>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_user.email %></div>
        </li>
        <%= image_tag(current_user.avatar, alt: "Avatar", class: 'navbar-brand', style: "height:40px; border-radius: 100%;")%>
        <li class="nav-item">
          <%= link_to("Sair", destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/user/profile/show.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <h5 class="card-header"><%= image_tag(current_user.avatar, class: "ui-w-100-forced rounded-circle mr-3", style: "width: 90px; height: 90px") %> <%= current_user.name %></h5>
      <div class="card-body">
        Email:
        <p class="card-text text-muted"><%= current_user.email %></p>
        Telefone:
        <p class="card-text text-muted"><%= current_user.phone %></p>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <%= form_with(model: [:user, @post], local: true) do |f| %>
          <%= render("layouts/form_errors", record: @post) %>
          <div class="form-group">
            <label for="exempleInputEmail1">Texto</label>
            <%= f.text_area :body, rows: 5, class: "form-control", placeholder: "Digite seu texto..." %>
          </div>
          <button type="submit" class="btn btn-primary">Postar</button>
        <% end %>
      </div>
    </div>
    <% current_user.posts.order(created_at: :desc).each do |post| %>
      <div class="card text-white bg-dark mb-3 mt-3">
        <div class="card-header"><%= post.user.name %></div>
        <div class="card-body">
          <small class="text-muted"><%= post.created_at.strftime("%d/%m/%T - %H:%M") %></small>
          <p class="card-text"><%= post.body %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/timeline/index.html.erb
<h2>TIMELINE</h2>